// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUP1K-m5SCeUwDM88iyzcFOUv3Agq2nM',
    appId: '1:553305287728:web:e7be7dfba834295df8d1f5',
    messagingSenderId: '553305287728',
    projectId: 'notes-app-69843',
    authDomain: 'notes-app-69843.firebaseapp.com',
    storageBucket: 'notes-app-69843.firebasestorage.app',
    measurementId: 'G-3BM4D9B4ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcNQp5UbFFNnwAAoYoN8TE3J-e6PJFeHk',
    appId: '1:553305287728:android:4648b063f19b256ff8d1f5',
    messagingSenderId: '553305287728',
    projectId: 'notes-app-69843',
    storageBucket: 'notes-app-69843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHf9KLqQPHschzJybHLX8ZZ0tL8NQgBX8',
    appId: '1:553305287728:ios:53700cb7676c1a9ff8d1f5',
    messagingSenderId: '553305287728',
    projectId: 'notes-app-69843',
    storageBucket: 'notes-app-69843.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHf9KLqQPHschzJybHLX8ZZ0tL8NQgBX8',
    appId: '1:553305287728:ios:53700cb7676c1a9ff8d1f5',
    messagingSenderId: '553305287728',
    projectId: 'notes-app-69843',
    storageBucket: 'notes-app-69843.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdUP1K-m5SCeUwDM88iyzcFOUv3Agq2nM',
    appId: '1:553305287728:web:41ba7155d0316750f8d1f5',
    messagingSenderId: '553305287728',
    projectId: 'notes-app-69843',
    authDomain: 'notes-app-69843.firebaseapp.com',
    storageBucket: 'notes-app-69843.firebasestorage.app',
    measurementId: 'G-ZNY70VN89K',
  );

}